import { MigrationInterface, QueryRunner } from "typeorm";

export class MYMigration1764690527552 implements MigrationInterface {
    name = 'MYMigration1764690527552'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."apprentice_evaluation_evaluation_enum" AS ENUM('EXCELENTE', 'BIEN', 'REGULAR', 'MAL', 'INSUFICIENTE')`);
        await queryRunner.query(`CREATE TABLE "apprentice_evaluation" ("apprentice_id" character varying NOT NULL, "date" date NOT NULL, "evaluation" "public"."apprentice_evaluation_evaluation_enum" NOT NULL, CONSTRAINT "PK_21a93e6458c61104a96eab0c4cc" PRIMARY KEY ("apprentice_id", "date"))`);
        await queryRunner.query(`CREATE TABLE "group_activity" ("group_id" character varying NOT NULL, "activity_id" character varying NOT NULL, "confirmation" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9748da3244593021412dd7d2111" PRIMARY KEY ("group_id", "activity_id"))`);
        await queryRunner.query(`CREATE TABLE "activity_date" ("activity_id" character varying NOT NULL, "date" TIMESTAMP NOT NULL, CONSTRAINT "PK_bffe34dcbace688306708782116" PRIMARY KEY ("activity_id", "date"))`);
        await queryRunner.query(`CREATE TABLE "responsible_entity" ("id" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_9d07505368d964971530b1c59b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_responsible" ("activity_id" character varying NOT NULL, "responsible_id" character varying NOT NULL, CONSTRAINT "PK_335717b2058131d2c70875fc8a4" PRIMARY KEY ("activity_id", "responsible_id"))`);
        await queryRunner.query(`CREATE TABLE "place_entity" ("id" character varying NOT NULL, "place" character varying NOT NULL, CONSTRAINT "PK_46823ff82e049f53a704e34b65d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_place" ("activity_id" character varying NOT NULL, "place_id" character varying NOT NULL, CONSTRAINT "PK_89ef778698639d1d63bbd0a2cfe" PRIMARY KEY ("activity_id", "place_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."income_incometype_enum" AS ENUM('EFECTIVO', 'TRANSFERENCIA_BANCARIA', 'TARJETA_CREDITO', 'TARJETA_DEBITO', 'CHEQUE', 'DEPOSITO', 'MONEDA_DIGITAL', 'PAYPAL', 'TRANSFERENCIA_ELECTRONICA', 'OTRO')`);
        await queryRunner.query(`CREATE TABLE "income" ("id" character varying NOT NULL, "activity_id" character varying NOT NULL, "incomeType" "public"."income_incometype_enum" NOT NULL DEFAULT 'EFECTIVO', "mount" numeric(10,2) NOT NULL, "date" date NOT NULL, "responsible" character varying NOT NULL, CONSTRAINT "PK_d07b89e41c82c069dd5a058f848" PRIMARY KEY ("id", "activity_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_entity_classification_enum" AS ENUM('CLASE_VOCAL', 'CLASE_BAILE', 'CLASE_RAP', 'ENTRENAMIENTO_FÍSICO', 'CONCIERTO_PRÁCTICA', 'GRABACIÓN_VÍDEO', 'GRABACIÓN_AUDIO', 'SESIÓN_FOTOGRÁFICA', 'ENSAYO_COREOGRAFÍA', 'ENTREVISTA', 'REUNIÓN_FAN', 'EVENTO_PROMOCIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_entity_type_enum" AS ENUM('INDIVIDUAL', 'GRUPAL')`);
        await queryRunner.query(`CREATE TABLE "activity_entity" ("id" character varying NOT NULL, "classification" "public"."activity_entity_classification_enum" NOT NULL, "type" "public"."activity_entity_type_enum" NOT NULL, CONSTRAINT "PK_ae8895d1732201c8184c61a24e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artist_activity" ("artist_id" character varying NOT NULL, "activity_id" character varying NOT NULL, "confirmation" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_39e948bd786f20c56135468db0d" PRIMARY KEY ("artist_id", "activity_id"))`);
        await queryRunner.query(`CREATE TABLE "artist_agency_membership" ("artist_id" character varying NOT NULL, "agency_id" character varying NOT NULL, "interval_id" character varying NOT NULL, CONSTRAINT "PK_f36c56ce97892848cde3e30d2fe" PRIMARY KEY ("artist_id", "agency_id", "interval_id"))`);
        await queryRunner.query(`CREATE TABLE "interval_entity" ("id" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, CONSTRAINT "PK_bc2421f3d76f6e9203eaa0c1ebf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artist_group_membership" ("group_id" character varying NOT NULL, "interval_id" character varying NOT NULL, "artist_id" character varying NOT NULL, "rol" character varying NOT NULL, "fecha_debut_art" date NOT NULL, CONSTRAINT "PK_04164f0a0525b31353b755e8751" PRIMARY KEY ("group_id", "interval_id", "artist_id"))`);
        await queryRunner.query(`CREATE TABLE "artist_group_collaboration" ("artist_id" character varying NOT NULL, "group_id" character varying NOT NULL, "date_id" character varying NOT NULL, CONSTRAINT "PK_a3340b837a80a6e58b04cecfd26" PRIMARY KEY ("artist_id", "group_id", "date_id"))`);
        await queryRunner.query(`CREATE TABLE "date_entity" ("id" character varying NOT NULL, "date" date NOT NULL, CONSTRAINT "PK_3b79937ff555c5865053d931f42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "artist_collaboration" ("artist1_id" character varying NOT NULL, "artist2_id" character varying NOT NULL, "date_id" character varying NOT NULL, CONSTRAINT "PK_3ed65f58b09d0597421307bac9e" PRIMARY KEY ("artist1_id", "artist2_id", "date_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."artist_status_enum" AS ENUM('ACTIVO', 'EN_PAUSA', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "artist" ("id" character varying NOT NULL, "stage_name" character varying NOT NULL, "status" "public"."artist_status_enum" NOT NULL, "birth_date" TIMESTAMP NOT NULL, "transition_date" TIMESTAMP NOT NULL, "group_id" character varying NOT NULL, "apprentice_id" character varying NOT NULL, CONSTRAINT "REL_3d65c831523a46b258854bc470" UNIQUE ("apprentice_id"), CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."apprentice_status_enum" AS ENUM('EN_ENTRENAMIENTO', 'PROCESO_DE_SELECCION', 'TRANSFERIDO')`);
        await queryRunner.query(`CREATE TYPE "public"."apprentice_traininglevel_enum" AS ENUM('PRINCIPIANTE', 'INTERMEDIO', 'AVANZADO')`);
        await queryRunner.query(`CREATE TABLE "apprentice" ("id" character varying NOT NULL, "full_name" character varying NOT NULL, "entry_date" TIMESTAMP NOT NULL, "age" integer NOT NULL, "status" "public"."apprentice_status_enum" NOT NULL DEFAULT 'EN_ENTRENAMIENTO', "trainingLevel" "public"."apprentice_traininglevel_enum" NOT NULL DEFAULT 'PRINCIPIANTE', "agency_id" character varying NOT NULL, CONSTRAINT "PK_b27a0b1a290b9d3fa27c7251e10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agency" ("id" character varying NOT NULL, "place" character varying NOT NULL, "date_fundation" TIMESTAMP NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_ab1244724d1c216e9720635a2e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_status_enum" AS ENUM('ACTIVO', 'EN_PAUSA', 'DISUELTO')`);
        await queryRunner.query(`CREATE TABLE "group" ("id" character varying NOT NULL, "name" character varying NOT NULL, "status" "public"."group_status_enum" NOT NULL DEFAULT 'EN_PAUSA', "concept" character varying NOT NULL, "visualconcept" character varying NOT NULL, "debutDate" date NOT NULL, "memberNumber" integer NOT NULL, "is_created" boolean NOT NULL, "proposed_by_artist_id" character varying, "agencyId" character varying, CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "award_entity" ("id" character varying NOT NULL, "name" character varying NOT NULL, "date" date NOT NULL, "album_id" character varying NOT NULL, CONSTRAINT "PK_80bc0e716eba2a7b5ccf14d281a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "album_entity" ("id" character varying NOT NULL, "title" character varying NOT NULL, "releaseDate" TIMESTAMP NOT NULL, "mainProducer" character varying NOT NULL, "copiesSold" integer NOT NULL, "numberOfTracks" integer NOT NULL, "group_id" character varying, "artist_id" character varying, CONSTRAINT "PK_319a74c2085b42849b15412a3bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "billboardList" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "entry_date" TIMESTAMP NOT NULL, CONSTRAINT "PK_5b4576e51aef7706a66fb729c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "song_billboard" ("song_id" integer NOT NULL, "billboard_list_id" integer NOT NULL, "puesto" integer NOT NULL, CONSTRAINT "PK_695c061c9603f167b33e6d188eb" PRIMARY KEY ("song_id", "billboard_list_id"))`);
        await queryRunner.query(`CREATE TABLE "song" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "entry_date" TIMESTAMP NOT NULL, "album_id" character varying, CONSTRAINT "PK_baaa977f861cce6ff954ccee285" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('AGENCY_MANAGER', 'ARTIST', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "isActive" boolean NOT NULL, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contract_entity_status_enum" AS ENUM('ACTIVO', 'FINALIZADO', 'EN_RENOVACION', 'RESCINDIDO')`);
        await queryRunner.query(`CREATE TABLE "contract_entity" ("contract_id" character varying NOT NULL, "agencyID" character varying NOT NULL, "artistID" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "status" "public"."contract_entity_status_enum" NOT NULL DEFAULT 'ACTIVO', "conditions" character varying NOT NULL, "distributionPercentage" numeric NOT NULL, CONSTRAINT "PK_da2ce5de70d2a871a3fc2021126" PRIMARY KEY ("contract_id", "agencyID", "artistID", "startDate", "endDate"))`);
        await queryRunner.query(`ALTER TABLE "apprentice_evaluation" ADD CONSTRAINT "FK_16c854b5a70d3a2e3d16b01dd91" FOREIGN KEY ("apprentice_id") REFERENCES "apprentice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_activity" ADD CONSTRAINT "FK_20370cab416c7603d4a0d1b9df4" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_activity" ADD CONSTRAINT "FK_4928cee72972df0b5e7dae48f60" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_date" ADD CONSTRAINT "FK_00ab4bf76bfef1ca310d304eb18" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_responsible" ADD CONSTRAINT "FK_ea526e633846beb259ef752d03f" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_responsible" ADD CONSTRAINT "FK_e253eaf811029e990c3f0f9d276" FOREIGN KEY ("responsible_id") REFERENCES "responsible_entity"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_place" ADD CONSTRAINT "FK_2d12d8cf2a3b2d1e33dec17617b" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_place" ADD CONSTRAINT "FK_3c29c7947b897bc909fef6204ff" FOREIGN KEY ("place_id") REFERENCES "place_entity"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "income" ADD CONSTRAINT "FK_266797c0c4aab3568423864a7ce" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_activity" ADD CONSTRAINT "FK_76e4eec8a8f94728d559f05e2f7" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_activity" ADD CONSTRAINT "FK_c071da472f85829afa1df76f83c" FOREIGN KEY ("activity_id") REFERENCES "activity_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" ADD CONSTRAINT "FK_d79a268e3f6c4885e4d3b9ddb8d" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" ADD CONSTRAINT "FK_4bcb8b2dc4ea4971a7bcaeada2f" FOREIGN KEY ("agency_id") REFERENCES "agency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" ADD CONSTRAINT "FK_401ed80373616182123b03349ce" FOREIGN KEY ("interval_id") REFERENCES "interval_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" ADD CONSTRAINT "FK_68d39df8b7427df1251193935ec" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" ADD CONSTRAINT "FK_51d77f50ec4a4ce8c190bb8abce" FOREIGN KEY ("interval_id") REFERENCES "interval_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" ADD CONSTRAINT "FK_cd7f111f6a9f0492aba3a3f1891" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" ADD CONSTRAINT "FK_e51e693877d141dcc518d9648a4" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" ADD CONSTRAINT "FK_37fc239cdb5ff46d6d004d16b77" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" ADD CONSTRAINT "FK_ab1f7014d0fcb3f5380c6591487" FOREIGN KEY ("date_id") REFERENCES "date_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" ADD CONSTRAINT "FK_ba5ca6d36300cafc45ff5bfef25" FOREIGN KEY ("artist1_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" ADD CONSTRAINT "FK_7440d93d48efd21cc5f756c8552" FOREIGN KEY ("artist2_id") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" ADD CONSTRAINT "FK_25a9e50dfa623606fad1e86739a" FOREIGN KEY ("date_id") REFERENCES "date_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "FK_3d65c831523a46b258854bc470d" FOREIGN KEY ("apprentice_id") REFERENCES "apprentice"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apprentice" ADD CONSTRAINT "FK_2fb829c287235cd0f5b7edefa58" FOREIGN KEY ("agency_id") REFERENCES "agency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_0ad37855210b18d8dd0699ad54e" FOREIGN KEY ("agencyId") REFERENCES "agency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_122939d81ddce427b91bbffc12d" FOREIGN KEY ("proposed_by_artist_id") REFERENCES "artist"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "award_entity" ADD CONSTRAINT "FK_c65459eb3b6459a84c86330cb73" FOREIGN KEY ("album_id") REFERENCES "album_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_entity" ADD CONSTRAINT "FK_eeea3e3782cd4f3b0835eb63bb6" FOREIGN KEY ("group_id") REFERENCES "group"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_entity" ADD CONSTRAINT "FK_10ea30022a530d8d0abd4250ff8" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song_billboard" ADD CONSTRAINT "FK_f86489de1eda21a0e1ad2a987b0" FOREIGN KEY ("song_id") REFERENCES "song"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song_billboard" ADD CONSTRAINT "FK_b742d8c0dfb486f96f1eb711834" FOREIGN KEY ("billboard_list_id") REFERENCES "billboardList"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "song" ADD CONSTRAINT "FK_c1b6644942ac9914001543107d5" FOREIGN KEY ("album_id") REFERENCES "album_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contract_entity" ADD CONSTRAINT "FK_7660b02f35c634a23d7ded1c6a0" FOREIGN KEY ("agencyID") REFERENCES "agency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contract_entity" ADD CONSTRAINT "FK_3a49e460a30517dfe027ab50d04" FOREIGN KEY ("artistID") REFERENCES "artist"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contract_entity" DROP CONSTRAINT "FK_3a49e460a30517dfe027ab50d04"`);
        await queryRunner.query(`ALTER TABLE "contract_entity" DROP CONSTRAINT "FK_7660b02f35c634a23d7ded1c6a0"`);
        await queryRunner.query(`ALTER TABLE "song" DROP CONSTRAINT "FK_c1b6644942ac9914001543107d5"`);
        await queryRunner.query(`ALTER TABLE "song_billboard" DROP CONSTRAINT "FK_b742d8c0dfb486f96f1eb711834"`);
        await queryRunner.query(`ALTER TABLE "song_billboard" DROP CONSTRAINT "FK_f86489de1eda21a0e1ad2a987b0"`);
        await queryRunner.query(`ALTER TABLE "album_entity" DROP CONSTRAINT "FK_10ea30022a530d8d0abd4250ff8"`);
        await queryRunner.query(`ALTER TABLE "album_entity" DROP CONSTRAINT "FK_eeea3e3782cd4f3b0835eb63bb6"`);
        await queryRunner.query(`ALTER TABLE "award_entity" DROP CONSTRAINT "FK_c65459eb3b6459a84c86330cb73"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_122939d81ddce427b91bbffc12d"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_0ad37855210b18d8dd0699ad54e"`);
        await queryRunner.query(`ALTER TABLE "apprentice" DROP CONSTRAINT "FK_2fb829c287235cd0f5b7edefa58"`);
        await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "FK_3d65c831523a46b258854bc470d"`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" DROP CONSTRAINT "FK_25a9e50dfa623606fad1e86739a"`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" DROP CONSTRAINT "FK_7440d93d48efd21cc5f756c8552"`);
        await queryRunner.query(`ALTER TABLE "artist_collaboration" DROP CONSTRAINT "FK_ba5ca6d36300cafc45ff5bfef25"`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" DROP CONSTRAINT "FK_ab1f7014d0fcb3f5380c6591487"`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" DROP CONSTRAINT "FK_37fc239cdb5ff46d6d004d16b77"`);
        await queryRunner.query(`ALTER TABLE "artist_group_collaboration" DROP CONSTRAINT "FK_e51e693877d141dcc518d9648a4"`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" DROP CONSTRAINT "FK_cd7f111f6a9f0492aba3a3f1891"`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" DROP CONSTRAINT "FK_51d77f50ec4a4ce8c190bb8abce"`);
        await queryRunner.query(`ALTER TABLE "artist_group_membership" DROP CONSTRAINT "FK_68d39df8b7427df1251193935ec"`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" DROP CONSTRAINT "FK_401ed80373616182123b03349ce"`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" DROP CONSTRAINT "FK_4bcb8b2dc4ea4971a7bcaeada2f"`);
        await queryRunner.query(`ALTER TABLE "artist_agency_membership" DROP CONSTRAINT "FK_d79a268e3f6c4885e4d3b9ddb8d"`);
        await queryRunner.query(`ALTER TABLE "artist_activity" DROP CONSTRAINT "FK_c071da472f85829afa1df76f83c"`);
        await queryRunner.query(`ALTER TABLE "artist_activity" DROP CONSTRAINT "FK_76e4eec8a8f94728d559f05e2f7"`);
        await queryRunner.query(`ALTER TABLE "income" DROP CONSTRAINT "FK_266797c0c4aab3568423864a7ce"`);
        await queryRunner.query(`ALTER TABLE "activity_place" DROP CONSTRAINT "FK_3c29c7947b897bc909fef6204ff"`);
        await queryRunner.query(`ALTER TABLE "activity_place" DROP CONSTRAINT "FK_2d12d8cf2a3b2d1e33dec17617b"`);
        await queryRunner.query(`ALTER TABLE "activity_responsible" DROP CONSTRAINT "FK_e253eaf811029e990c3f0f9d276"`);
        await queryRunner.query(`ALTER TABLE "activity_responsible" DROP CONSTRAINT "FK_ea526e633846beb259ef752d03f"`);
        await queryRunner.query(`ALTER TABLE "activity_date" DROP CONSTRAINT "FK_00ab4bf76bfef1ca310d304eb18"`);
        await queryRunner.query(`ALTER TABLE "group_activity" DROP CONSTRAINT "FK_4928cee72972df0b5e7dae48f60"`);
        await queryRunner.query(`ALTER TABLE "group_activity" DROP CONSTRAINT "FK_20370cab416c7603d4a0d1b9df4"`);
        await queryRunner.query(`ALTER TABLE "apprentice_evaluation" DROP CONSTRAINT "FK_16c854b5a70d3a2e3d16b01dd91"`);
        await queryRunner.query(`DROP TABLE "contract_entity"`);
        await queryRunner.query(`DROP TYPE "public"."contract_entity_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "song"`);
        await queryRunner.query(`DROP TABLE "song_billboard"`);
        await queryRunner.query(`DROP TABLE "billboardList"`);
        await queryRunner.query(`DROP TABLE "album_entity"`);
        await queryRunner.query(`DROP TABLE "award_entity"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP TYPE "public"."group_status_enum"`);
        await queryRunner.query(`DROP TABLE "agency"`);
        await queryRunner.query(`DROP TABLE "apprentice"`);
        await queryRunner.query(`DROP TYPE "public"."apprentice_traininglevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."apprentice_status_enum"`);
        await queryRunner.query(`DROP TABLE "artist"`);
        await queryRunner.query(`DROP TYPE "public"."artist_status_enum"`);
        await queryRunner.query(`DROP TABLE "artist_collaboration"`);
        await queryRunner.query(`DROP TABLE "date_entity"`);
        await queryRunner.query(`DROP TABLE "artist_group_collaboration"`);
        await queryRunner.query(`DROP TABLE "artist_group_membership"`);
        await queryRunner.query(`DROP TABLE "interval_entity"`);
        await queryRunner.query(`DROP TABLE "artist_agency_membership"`);
        await queryRunner.query(`DROP TABLE "artist_activity"`);
        await queryRunner.query(`DROP TABLE "activity_entity"`);
        await queryRunner.query(`DROP TYPE "public"."activity_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_entity_classification_enum"`);
        await queryRunner.query(`DROP TABLE "income"`);
        await queryRunner.query(`DROP TYPE "public"."income_incometype_enum"`);
        await queryRunner.query(`DROP TABLE "activity_place"`);
        await queryRunner.query(`DROP TABLE "place_entity"`);
        await queryRunner.query(`DROP TABLE "activity_responsible"`);
        await queryRunner.query(`DROP TABLE "responsible_entity"`);
        await queryRunner.query(`DROP TABLE "activity_date"`);
        await queryRunner.query(`DROP TABLE "group_activity"`);
        await queryRunner.query(`DROP TABLE "apprentice_evaluation"`);
        await queryRunner.query(`DROP TYPE "public"."apprentice_evaluation_evaluation_enum"`);
    }

}
